### PR TITLE
build: fix fedora onbuild test

### PR DESCRIPTION
**Pull request by helio-frota**

### CODE REVIEW

**Comment by helio-frota** [comment]
This connects to #109 
Also the example app was added.
So this will close that issue.

**Review by lance — CHANGES_REQUESTED** [review]
I think we need to start making the `.onbuild` files part of the normal testing that is done via the `build.sh` script. When I run the following command, it fails.

```sh
$ make test ONBUILD=true OS=fedora
```

This makes sense, because the `.onbuild` versions have not historically been tested as a part of the regular `build.sh` fun. But I think this is problematic, since it's easy to forget testing `.onbuild` locally when developing, and it only ever really happens in CI.

Now seems as good of a time as any to add this test to the regular `build.sh` test loop [here](https://github.com/bucharest-gold/origin-s2i-nodejs/blob/8ac112b6d95468eed9775cb462ac301ab2b3a589/build/build.sh#L77-L89).

This will mean further modifications for the test framework, so that the Dockerfile in `test/s2i-nodejs` can be modified dynamically. 

Also, if I am reading the code correctly, it seems as though the test application/docker image is built, but never actually run and verified. It probably should be.

**Comment by helio-frota** [comment]
Yes, I run `make onbuild OS=fedora` then, I run `./test/onbuild-test` so, this `onbuild-test` will look for the local image.

`make tests` currently generates the `candidate` images.

So currently we have onbuild tests only on CI.

>  ...since it's easy to forget testing .onbuild locally when developing, and it only ever really happens in CI.
> ...Now seems as good of a time as any to add this test to the regular build.sh...

makes sense.
Thanks !

**Comment by lance** [comment]
Connects to #109

**Pull request closed without merging**
